version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 138958072377.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t aws-devops-youtube .
      - docker tag aws-devops-youtube:latest 138958072377.dkr.ecr.us-east-1.amazonaws.com/aws-devops-youtube:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 138958072377.dkr.ecr.us-east-1.amazonaws.com/aws-devops-youtube:latest